import com.android.build.api.artifact.SingleArtifact
import com.android.build.api.variant.BuiltArtifactsLoader
import com.android.build.api.variant.HasUnitTest
import com.google.gms.googleservices.GoogleServicesPlugin.MissingGoogleServicesStrategy
import java.io.File
import java.lang.ProcessHandle
import java.nio.file.Files
import java.security.MessageDigest
import java.util.Properties
import java.util.concurrent.TimeUnit
import java.util.zip.ZipFile
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.provider.Provider
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.testing.Test as GradleTest
import org.gradle.kotlin.dsl.register

plugins {
  alias(libs.plugins.chaquopy)
  alias(libs.plugins.android.application)
  alias(libs.plugins.kotlin.compose)
  alias(libs.plugins.google.devtools.ksp)
  alias(libs.plugins.roborazzi)
  alias(libs.plugins.secrets)
  alias(libs.plugins.google.services)
  alias(libs.plugins.firebase.crashlytics)
  alias(libs.plugins.kover)
}

fun intProperty(name: String): Int? = providers.gradleProperty(name).orNull?.toIntOrNull()

kover {
  reports {
    total {
      html { onCheck = false }
      xml { onCheck = true }
      verify {
        rule {
          minBound(intProperty("kover.instructionThreshold") ?: 80)
        }
        rule {
          minBound(intProperty("kover.branchThreshold") ?: 70, coverageUnits = kotlinx.kover.gradle.plugin.dsl.CoverageUnit.BRANCH)
        }
      }
    }
  }
}

// The Kover JVM agent rewrites every class a test JVM loads. Robolectric loads
// the Android framework and the Room cohorts fork a fresh JVM per class, so
// local test loops pay that instrumentation tax for a binary report only CI
// consumes. Keep coverage in CI and for invocations that explicitly ask for a
// Kover task; ordinary local test and build runs skip it.
val coverageRequested =
  !System.getenv("CI").isNullOrEmpty() ||
    gradle.startParameter.taskNames.any { it.contains("kover", ignoreCase = true) }
if (!coverageRequested) {
  kover {
    currentProject {
      instrumentation {
        disabledForAll = true
      }
    }
  }
}

// wayfinder #47: export Room schemas into the repo so future migrations are
// reviewable and verifiable. KSP writes the JSON for the current database
// version on every build.
ksp {
  arg("room.schemaLocation", "$projectDir/schemas")
}

android {
  namespace = "com.slukhayka.audiobooks"
  compileSdk { version = release(36) { minorApiLevel = 1 } }

  defaultConfig {
    applicationId = "com.slukhayka.audiobooks"
    minSdk = 24
    // #779 — Chaquopy ships native CPython per ABI, so an explicit list is required.
    ndk { abiFilters += listOf("arm64-v8a", "x86_64") }
    targetSdk = 36
    // spec-29 T1 (#210): first release under the permanent applicationId.
    // versionCode grows monotonically across the Слухайка line (v1.0 was 1).
    versionCode = 30
    versionName = "1.4.2"

    // Device tests run against their OWN database file (see the runner):
    // a test that wipes and reseeds the database for determinism must never
    // wipe the listener's library on a real phone.
    testInstrumentationRunner = "com.slukhayka.audiobooks.IsolatedDatabaseTestRunner"
  }

  signingConfigs {
    create("release") {
      // CI (release.yml) passes KEYSTORE_PATH/STORE_PASSWORD/KEY_PASSWORD as
      // env vars — those win. Locally we fall back to a gitignored
      // keystore.properties (generated by scripts/generate-keystore.sh), so
      // `./gradlew :app:assembleRelease` works with no env setup.
      val propsFile = rootProject.file("keystore.properties")
      val props = Properties().apply {
        if (propsFile.exists()) propsFile.inputStream().use { load(it) }
      }
      val keystorePath = System.getenv("KEYSTORE_PATH")
        ?: props.getProperty("keystorePath")
        ?: "my-upload-key.jks"
      // Resolve relative paths against the repo root (the signing config
      // lives in the :app module, whose own dir is app/).
      storeFile = rootProject.file(keystorePath)
      storePassword = System.getenv("STORE_PASSWORD") ?: props.getProperty("storePassword")
      keyAlias = System.getenv("KEY_ALIAS") ?: props.getProperty("keyAlias") ?: "upload"
      keyPassword = System.getenv("KEY_PASSWORD") ?: props.getProperty("keyPassword")
    }
  }

  buildTypes {
    debug {
      // Install developer builds next to the signed release app so on-device
      // testing never requires uninstalling (and losing) the listener's data.
      applicationIdSuffix = ".debug"
      buildConfigField("boolean", "CRASH_REPORTING_ENABLED", "false")
    }
    release {
      buildConfigField("boolean", "CRASH_REPORTING_ENABLED", "true")
      isCrunchPngs = false
      isMinifyEnabled = false
      proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
      signingConfig = signingConfigs.getByName("release")
    }
    // Debug uses AGP's default debug signing (auto-generated ~/.android/debug.keystore).
    // A custom signingConfig pointing at a gitignored ${rootDir}/debug.keystore was
    // removed — it broke every fresh checkout and CI run at :app:validateSigningDebug.
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
  }
  buildFeatures {
    compose = true
    buildConfig = true
  }
  testOptions {
    unitTests {
      isIncludeAndroidResources = true
      all {
        // Robolectric's NATIVE graphics runtime (the roborazzi snapshots) loads
        // a JNI library; on a modern JDK the load fails unless native access is
        // granted explicitly. Without this the snapshot tests die in
        // DefaultNativeRuntimeLoader instead of comparing images.
        it.jvmArgs("--enable-native-access=ALL-UNNAMED")
      }
    }
  }
  lint {
    // #386 — the inherited lint debt is accepted as a checked-in baseline so
    // `lintDebug` passes and CI can adopt it. The app UI is intentionally
    // Ukrainian (CONTEXT.md) and `values-pl` is only a partial Material3
    // override for TalkBack, so MissingTranslation there is a false positive;
    // the remaining UnsafeOptInUsageError/NewApi entries are pinned for a
    // separate cleanup. A NEW issue outside the baseline still fails.
    baseline = file("lint-baseline.xml")
  }
}

// spec-29 T1 (#210): the release artifact carries the version in its name
// (slukhayka-v1.1.apk, v1.2, v1.3, ...) so downloads are unambiguous across
// releases (US-13). AGP 9 removed the old outputFileName hook, so this reacts
// to SingleArtifact.APK creation with the public Variant API (the documented
// listenToArtifacts replacement) and copies the built APK to the versioned
// name under app/build/outputs/renamed_apks/release/. The name comes from the
// APK's own metadata (BuiltArtifact.versionName), so it can never drift from
// what is actually inside the file. Debug keeps its AGP default name.
androidComponents {
  onVariants(selector().withBuildType("release")) { variant ->
    val renameTask = tasks.register<RenameReleaseApk>("renameReleaseApk") {
      output.set(layout.buildDirectory.dir("outputs/renamed_apks/release"))
      builtArtifactsLoader.set(variant.artifacts.getBuiltArtifactsLoader())
    }
    variant.artifacts.use(renameTask).wiredWith { it.input }.toListenTo(SingleArtifact.APK)
  }
}

// Copies the built release APK to slukhayka-v<versionName>.apk. The input is
// the directory AGP publishes for SingleArtifact.APK; the loader enumerates
// the APKs inside it with their metadata (single APK in our case — no splits).
abstract class RenameReleaseApk : DefaultTask() {
  @get:InputDirectory
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val input: DirectoryProperty

  @get:OutputDirectory
  abstract val output: DirectoryProperty

  @get:Internal
  abstract val builtArtifactsLoader: Property<BuiltArtifactsLoader>

  @TaskAction
  fun rename() {
    val builtArtifacts = builtArtifactsLoader.get().load(input.get())
      ?: throw GradleException("Cannot load built APKs from ${input.get()}")
    builtArtifacts.elements.forEach { artifact ->
      val targetName = "slukhayka-v${artifact.versionName}.apk"
      File(artifact.outputFile).copyTo(output.get().file(targetName).asFile, overwrite = true)
    }
  }
}

// Configure the Secrets Gradle Plugin to use .env and .env.example files
// to match the convention used in Web projects.
secrets {
  propertiesFileName = ".env"
  defaultPropertiesFileName = ".env.example"
}

googleServices { missingGoogleServicesStrategy = MissingGoogleServicesStrategy.WARN }

// Some unused dependencies are commented out below instead of being removed.
// This makes it easy to add them back in the future if needed.
dependencies {
  // Spec 2026-08-26: ONE protobuf runtime in the APK — protobuf-javalite
  // 3.25.5, the version Firestore's protolite codegen pairs with and the
  // version the JVM probe verified NewPipeExtractor extracts fully on.
  // Three artifacts were fighting over com.google.protobuf classes —
  // Firebase's protolite (old, stripped: NewPipe died invisibly on its
  // missing InvalidProtocolBufferException), NewPipe's javalite 4.35.1, and
  // Firestore's transitive javalite 3.25.1 — and the APK build refuses
  // duplicates. protolite is excluded entirely; its NON-protobuf half (the
  // googleapis common protos Firestore decodes — com.google.type.LatLng et
  // al., without which GeoPoint/WriteBatch crash) ships as the surgical
  // app/libs/protolite-googleapis.jar with com/google/protobuf stripped.
  configurations.all {
    exclude(group = "com.google.firebase", module = "protolite-well-known-types")
    resolutionStrategy {
      force("com.google.protobuf:protobuf-javalite:3.25.5")
    }
  }
  implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"))))
  implementation(platform(libs.androidx.compose.bom))
  implementation(platform(libs.firebase.bom))
  // implementation(libs.accompanist.permissions)
  implementation(libs.androidx.activity.compose)
  // implementation(libs.androidx.camera.camera2)
  // implementation(libs.androidx.camera.core)
  // implementation(libs.androidx.camera.lifecycle)
  // implementation(libs.androidx.camera.view)
  implementation(libs.androidx.compose.material.icons.core)
  implementation(libs.androidx.compose.material.icons.extended)
  implementation(libs.androidx.compose.material3)
  implementation(libs.androidx.compose.ui)
  implementation(libs.androidx.compose.ui.graphics)
  implementation(libs.androidx.compose.ui.tooling.preview)
  implementation(libs.androidx.core.ktx)
  implementation(libs.androidx.documentfile)
  implementation(libs.androidx.glance.appwidget)
  implementation(libs.androidx.glance.material3)
  // Spec-38 T3 (#255): the official webkit controller rides the privacy route
  // (ProxyController) and the document-start sensor lockdown (WebViewCompat).
  implementation(libs.androidx.webkit)
  implementation(libs.androidx.work.runtime)
  // Spec-40 #276 (t2): the BiometricPrompt gate for «Код відновлення профілю».
  implementation(libs.androidx.biometric)
  implementation(libs.androidx.media3.exoplayer)
  // #516 — playback data source on the shared OkHttp engine (app DNS/DoH,
  // privacy route, one identity). The DefaultHttpDataSource resolved names
  // through the system resolver and could not ride the route.
  implementation(libs.androidx.media3.datasource.okhttp)
  implementation(libs.androidx.media3.session)
  // ADR-0024: CastPlayer swaps in behind the MediaSession player seam while
  // casting; the receiver itself never touches the network (phone proxy).
  implementation(libs.androidx.media3.cast)
  implementation(libs.play.services.cast.framework)
  implementation(libs.nanohttpd)
  // implementation(libs.androidx.datastore.preferences)
  implementation(libs.androidx.lifecycle.runtime.compose)
  implementation(libs.androidx.lifecycle.runtime.ktx)
  implementation(libs.androidx.lifecycle.viewmodel.compose)
  implementation(libs.androidx.navigation.compose)
  // Spec-23 T4: the endless merged catalogue feed (Paging 3).
  implementation(libs.androidx.paging.runtime)
  implementation(libs.androidx.paging.compose)
  implementation(libs.androidx.room.ktx)
  implementation(libs.androidx.room.runtime)
  // Room's PagingSource DAO support (spec-23 T4 endless feed).
  implementation(libs.androidx.room.paging)
  implementation(libs.coil.compose)
  implementation(libs.converter.moshi)
  implementation(libs.firebase.ai)
  implementation(libs.firebase.crashlytics)
  // Spec-26 T5: the shared universe-knowledge base (Firestore free tier).
  // Requires a local (gitignored) google-services.json — without it the
  // shared layer is simply absent and the app works as before.
  // Spec-40 #275 (t1): the silent listener identity — Anonymous Auth
  // immediately elevated with generated credentials. Without Firebase keys
  // the identity degrades to the local-only profile.
  implementation(libs.firebase.auth)
  implementation(libs.firebase.appcheck.recaptcha)
  implementation(libs.kotlinx.coroutines.android)
  implementation(libs.kotlinx.coroutines.core)
  // spec-26 T1 (#175): on-device title translation for the Wikidata search
  // fallback — free, no API key, models download once per language pair.
  implementation(libs.mlkit.translate)
  implementation(libs.logging.interceptor)
  implementation(libs.moshi.kotlin)
  implementation(libs.okhttp)
  // Spec 2026-08-26: YouTube stream extraction for audio-less 4read pages —
  // the watch URL resolves to a progressive audio stream at play/download
  // time. Distribution is JitPack; rhino (deobfuscation) needs keep rules
  // under minification (see proguard-rules.pro).
  implementation(libs.newpipe.extractor)
  implementation(libs.firebase.firestore)

  // spec-38 T4 (#256): the RFC-8484 DoH resolver behind the privacy door —
  // same OkHttp version, one small artifact.
  implementation(libs.okhttp.dnsoverhttps)
  // Spec #361 («Проксі відтворення»): the embedded HTTP server inside the
  // playback proxy — plain sockets on one jar, no other surface.
  implementation(libs.nanohttpd)
  // implementation(libs.play.services.location)
  implementation(libs.retrofit)
  // spec-19 T3: on-device ONNX inference for the recommendation embedder
  // (ai.onnxruntime API). The Android artifact ships the model runner into
  // the app. The desktop (JVM) artifact is deliberately NOT a test
  // dependency — both jars contain the same ai.onnxruntime classes, so a
  // duplicate on the unit-test classpath would be ambiguous. The eval gate
  // script gets the desktop jar via its own configuration below.
  implementation(libs.onnxruntime.android)
  // ADR-0050 / #829 — the Telegram MTProto engine (TDLib), a PINNED prebuilt
  // AAR. It is fetched by downloadTdlib (version + sha256 pinned there) and
  // never committed; preBuild depends on that task so a clean checkout builds.
  implementation(files("libs/tdlib-1.8.67-d1085f9.aar"))

// spec-19 T3: the reproducible eval gate — runRecommendationEval. A host
// JVM script (test sources, so it reuses the fixtures + RecommendationEval)
// that loads the downloaded ONNX model and prints recall@20/NDCG@20 for
// baseline vs semantic, writing the report. The desktop onnxruntime jar
// (with host natives) comes only from this configuration; the android AAR
// is filtered out of the script's classpath.
val evalRuntime: Configuration by configurations.creating

dependencies {
  add("evalRuntime", libs.onnxruntime.jvm)
}

// spec-19 T3: fetches the ONNX model (int8 multilingual-e5-small, ~118 MB)
// into app/src/main/assets/models/e5/. Not committed (GitHub's 100 MB
// file limit); the embedder degrades to the keyword baseline when absent.
val downloadE5Model by tasks.registering(Exec::class) {
  group = "verification"
  description = "Downloads the multilingual-e5-small int8 ONNX model + tokenizer into app/src/main/assets/models/e5"
  val assetsDir = file("src/main/assets/models/e5")
  val modelFile = assetsDir.resolve("model.onnx")
  doFirst {
    assetsDir.mkdirs()
    if (modelFile.exists()) {
      logger.lifecycle("model.onnx already present — skipping download")
    } else {
      logger.lifecycle("downloading multilingual-e5-small int8 ONNX (~118 MB)...")
    }
  }
  commandLine(
    "bash", "-c",
    """
      set -e
      mkdir -p "${'$'}(pwd)/src/main/assets/models/e5"
      if [ ! -f src/main/assets/models/e5/model.onnx ]; then
        curl -sL --max-time 1200 -o src/main/assets/models/e5/model.onnx \
          "https://huggingface.co/Xenova/multilingual-e5-small/resolve/main/onnx/model_quantized.onnx"
      fi
      if [ ! -f src/main/assets/models/e5/tokenizer.json ]; then
        curl -sL --max-time 120 -o src/main/assets/models/e5/tokenizer.json \
          "https://huggingface.co/Xenova/multilingual-e5-small/resolve/main/tokenizer.json"
      fi
    """.trimIndent()
  )
}

// spec-26 T4: the residual-measurement gate — runUniverseResidualEval. A
// host JVM script (test sources, reusing the catalog fixture) that runs the
// fixed Wikidata provider against the live API with the real transport and
// classifies the misses by cause, writing the report. ML Kit (T1) is
// device-only, so the harness runs without the translator and says so.
val runUniverseResidualEval by tasks.registering(JavaExec::class) {
  group = "verification"
  description = "Runs the spec-26 T4 residual measurement over the catalog sample with the live Wikidata API; writes the report. Overrides via --args=\"path delayMs limit\"."
  mainClass.set("com.slukhayka.audiobooks.data.universe.RunUniverseResidualEval")
  dependsOn("compileDebugUnitTestKotlin", "processDebugUnitTestJavaRes")
  val compileTask = project.tasks.named("compileDebugUnitTestKotlin")
  val testOutput = (compileTask.get() as org.jetbrains.kotlin.gradle.tasks.KotlinCompile).destinationDirectory
  val resourcesOutput = project.layout.buildDirectory.dir("intermediates/java_res/debugUnitTest/processDebugUnitTestJavaRes/out")
  val testCp = project.configurations.getByName("debugUnitTestRuntimeClasspath")
  classpath = project.files(
    testOutput,
    resourcesOutput
  ) + project.files(testCp)
  args("${projectDir}/docs/specs/2026-08-16-universe-residual-report.md")
  isIgnoreExitValue = false
}

val runRecommendationEval by tasks.registering(JavaExec::class) {
  group = "verification"
  description = "Runs the spec-19 leave-one-out eval gate on saved fixtures with the real ONNX model; prints recall@20 / NDCG@20 and the GO/NO-GO decision."
  mainClass.set("com.slukhayka.audiobooks.data.recommend.RunRecommendationEval")
  // Classpath: test+main outputs, the desktop onnxruntime jar, and the
  // test runtime minus the android AAR (whose ai.onnxruntime classes share
  // the package — the desktop jar must win so its host natives load).
  // Compile the unit tests first (RunRecommendationEval lives in test
  // sources); its output dir carries the main class. The android onnxruntime
  // AAR is excluded from the runtime classpath so the desktop jar (with
  // host natives) resolves the ai.onnxruntime API.
  dependsOn("compileDebugKotlin", "compileDebugUnitTestKotlin", "processDebugUnitTestJavaRes")
  val mainCompileTask = project.tasks.named("compileDebugKotlin")
  val mainOutput = (mainCompileTask.get() as org.jetbrains.kotlin.gradle.tasks.KotlinCompile).destinationDirectory
  val compileTask = project.tasks.named("compileDebugUnitTestKotlin")
  val testOutput = (compileTask.get() as org.jetbrains.kotlin.gradle.tasks.KotlinCompile).destinationDirectory
  val resourcesOutput = project.layout.buildDirectory.dir("intermediates/java_res/debugUnitTest/processDebugUnitTestJavaRes/out")
  val testCp = project.configurations.getByName("debugUnitTestRuntimeClasspath")
    .files.filter { !it.name.contains("onnxruntime-android") }
  classpath = project.files(
    project.configurations.getByName("evalRuntime"),
    mainOutput,
    testOutput,
    resourcesOutput
  ) + project.files(testCp)
  // The model+tokenizer assets live under app/src/main/assets/models/e5;
  // the script resolves them relative to the project dir.
  args("${projectDir}/src/main/assets/models/e5")
  isIgnoreExitValue = false
}
  testImplementation(platform(libs.androidx.compose.bom))
  testImplementation(libs.androidx.compose.ui.test.junit4)
  testImplementation(libs.androidx.core)
  testImplementation(libs.androidx.junit)
  testImplementation(libs.junit)
  testImplementation(libs.kotlinx.coroutines.test)
  testImplementation(libs.robolectric)
  testImplementation(libs.roborazzi)
  testImplementation(libs.roborazzi.compose)
  testImplementation(libs.roborazzi.junit.rule)
  androidTestImplementation(platform(libs.androidx.compose.bom))
  androidTestImplementation(libs.androidx.compose.ui.test.junit4)
  androidTestImplementation(libs.androidx.compose.ui.test.junit4.accessibility)
  androidTestImplementation(libs.androidx.compose.ui.test.manifest)
  androidTestImplementation(libs.androidx.core)
  androidTestImplementation(libs.androidx.espresso.core)
  androidTestImplementation(libs.androidx.junit)
  androidTestImplementation(libs.androidx.runner)
  androidTestImplementation(libs.androidx.test.rules)
  androidTestImplementation(libs.kotlinx.coroutines.core)
  debugImplementation(libs.androidx.compose.ui.test.manifest)
  debugImplementation(libs.androidx.compose.ui.tooling)
  "ksp"(libs.androidx.room.compiler)
  "ksp"(libs.moshi.kotlin.codegen)
}

// Compose/Robolectric accessibility suites retain large rendered graphs.
// Keep the CI test worker from exhausting Gradle's default heap mid-suite.
tasks.withType<org.gradle.api.tasks.testing.Test>().configureEach {
  maxHeapSize = "2g"
}

// #423: one source of truth classifies every JVM test into exactly one public
// verification partition. Gradle and the local changed-test selector both
// consume this CLI, so a new test cannot silently disappear between them.
fun partitionTestClasses(
  partition: String,
  cohort: String = "all",
): List<String> {
  val arguments = mutableListOf(
    rootProject.file("scripts/test_partitions.py").absolutePath,
    "--root",
    rootProject.projectDir.absolutePath,
    "list",
    "--partition",
    partition,
    "--cohort",
    cohort,
  )
  return providers.exec {
    workingDir(rootProject.projectDir)
    commandLine("python3", *arguments.toTypedArray())
  }.standardOutput.asText.get().lineSequence().filter(String::isNotBlank).toList()
}

// The classifier shells out to Python and reads every test source, so resolve
// the lists lazily: a build pays for at most the one partition it runs, and
// non-test invocations (assemble, install, IDE sync) pay nothing at all.
fun partitionClasses(partition: String, cohort: String = "all"): Provider<List<String>> =
  providers.provider { partitionTestClasses(partition, cohort) }

// These aliases reuse AGP's standard Test task. Kover 0.9.9 instruments that
// task and emits one portable testDebugUnitTest.ic report in each CI job.
val partitionAliases = mapOf(
  "testPureJvm" to partitionClasses("pure-jvm"),
  "testRoomRobolectric" to partitionClasses("room-robolectric"),
  "testRoomNativeSdk35" to partitionClasses("room-robolectric", "native-sdk35"),
  "testRoomNativeSdk36" to partitionClasses("room-robolectric", "native-sdk36"),
  "testRoomNativeDefault" to partitionClasses("room-robolectric", "native-default"),
  "testRoomRobolectricOnly" to partitionClasses("room-robolectric", "non-native"),
  "testComposeRoborazzi" to partitionClasses("compose-roborazzi"),
)
val requestedPartitionAliases = gradle.startParameter.taskNames
  .map { it.substringAfterLast(':') }
  .filter(partitionAliases::containsKey)
  .distinct()
if (requestedPartitionAliases.size > 1) {
  throw GradleException("Run JVM test partitions separately, or use scripts/test-all.sh")
}

afterEvaluate {
  val baseJvmTest = tasks.named<org.gradle.api.tasks.testing.Test>("testDebugUnitTest")
  partitionAliases.forEach { (alias, _) ->
    tasks.register(alias) {
      group = "verification"
      description = when (alias) {
        "testPureJvm" -> "Runs pure JVM tests without Robolectric."
        "testRoomRobolectric" -> "Runs Room and other non-snapshot Robolectric tests."
        "testRoomNativeSdk35" -> "Runs the isolated SDK 35 native Room cohort."
        "testRoomNativeSdk36" -> "Runs the isolated SDK 36 native Room cohort."
        "testRoomNativeDefault" -> "Runs the isolated default-SDK native Room cohort."
        "testRoomRobolectricOnly" -> "Runs Robolectric tests that do not load native Room."
        else -> "Runs Compose and Roborazzi snapshot tests."
      }
      dependsOn(baseJvmTest)
    }
  }
  requestedPartitionAliases.singleOrNull()?.let { requestedAlias ->
    val selectedClasses = providers.gradleProperty("test.selectedClasses").orNull
      ?.split(',')
      ?.filter(String::isNotBlank)
      ?: partitionAliases.getValue(requestedAlias).get()
    check(selectedClasses.all { it in partitionAliases.getValue(requestedAlias).get() }) {
      "Selected classes must belong to the requested normal partition; controlled App uses python3 scripts/test-controlled-app.py run"
    }
    baseJvmTest.configure {
      systemProperty("slukhayka.test.workerCohort", requestedAlias)
      if (requestedAlias == "testRoomRobolectric") {
        // A fresh fork per class is intentionally stronger than grouping by
        // today's SDK list: future SDK/native SQLite combinations are isolated
        // automatically, without another hard-coded cohort table.
        maxParallelForks = 1
        forkEvery = 1
      } else if (requestedAlias.startsWith("testRoomNative")) {
        // Native SQLite keeps process-wide state even inside one Robolectric
        // SDK cohort. Reuse can therefore contaminate the next Room class.
        // Four fresh workers at a time match GitHub's public Linux runner and
        // retain isolation without serializing the entire SDK 36 cohort.
        maxParallelForks = 4
        forkEvery = 1
      } else {
        if (requestedAlias == "testPureJvm") {
          // Pure JVM tests do not initialise Android/Robolectric or native
          // SQLite state, so they can safely use the otherwise idle cores.
          // Cap the fan-out to keep local builds responsive and avoid making
          // CI workers contend for memory.
          maxParallelForks = minOf(4, Runtime.getRuntime().availableProcessors())
        } else {
          maxParallelForks = 1
        }
        if (requestedAlias == "testRoomRobolectricOnly") {
          // Robolectric keeps Android framework state for the life of a test
          // JVM. A fresh worker per class prevents that state from accumulating
          // across the long non-native accessibility suite.
          forkEvery = 1
        }
      }
      if (requestedAlias.startsWith("testRoomNative")) {
        val workerIdentityFile = layout.buildDirectory.file("test-worker-identities.tsv")
        systemProperty(
          "slukhayka.test.workerIdentityFile",
          workerIdentityFile.get().asFile.absolutePath,
        )
        // The probe is part of the CI contract. Declaring it as task output
        // makes Gradle restore it with a cached test result and rerun the task
        // when the report is absent instead of leaving upload-artifact empty.
        outputs.file(workerIdentityFile).withPropertyName("workerIdentityReport")
        doFirst { workerIdentityFile.get().asFile.delete() }
      }
      filter {
        isFailOnNoMatchingTests = true
        selectedClasses.forEach(::includeTestsMatching)
      }
    }
  }
}

tasks.register<Exec>("validateTestPartitions") {
  group = "verification"
  description = "Checks that every JVM test belongs to exactly one test partition."
  workingDir(rootProject.projectDir)
  commandLine(
    "python3",
    rootProject.file("scripts/test_partitions.py").absolutePath,
    "--root",
    rootProject.projectDir.absolutePath,
    "validate",
  )
}

// A coverage aggregation job downloads the partition IC files here and
// skips testDebugUnitTest while generating reports. Local Kover use continues
// to run the standard full test task as before.
kover {
  reports {
    total {
      providers.gradleProperty("kover.additionalBinaryReportsDir").orNull?.let { reportsDir ->
        additionalBinaryReports.addAll(
          fileTree(reportsDir) { include("**/*.ic") },
        )
      }
    }
  }
}

// #708 — the live metadata spike is manual only: forward its -D properties
// into the TEST JVM (Gradle CLI -D goes to the Gradle JVM, not the forked test
// JVM, so System.getProperty() in the test saw nothing and the gated test
// silently skipped).
tasks.withType<Test>().configureEach {
    listOf(
        "newpipe.spike", "spike.video", "spike.playlist", "spike.channel",
        // The scheduled YouTube contract canary (YouTubeContractCanaryTest)
        // rides the same forwarding so its gate and probe URL reach the JVM.
        "youtube.canary", "youtube.canary.video",
    ).forEach { key ->
        System.getProperty(key)?.let { systemProperty(key, it) }
    }
}

// #772 — test stdout must be visible: silent measurements are worse than none.
tasks.withType<Test>().configureEach {
    testLogging { showStandardStreams = true }
}

// #779 — the in-process Python engine. Version must match buildPython.
chaquopy {
    defaultConfig {
        version = "3.14"
        buildPython("python3.14")
    }
}

// #779 — Chaquopy 17.0.0 cannot live inside a configuration cache entry: the
// plugin starts an external Python process at configuration time and its
// `extract*PythonBuildPackages` task holds non-serializable Gradle internals.
// With the cache ON the build does not merely warn, it FAILS while storing the
// entry — verified 2026-09-13 — so `org.gradle.configuration-cache.problems=warn`
// does not help (that flag downgrades reported problems, not a store failure).
//
// `notCompatibleWithConfigurationCache` is Gradle's sanctioned escape hatch:
// instead of failing, Gradle disables the cache for the builds that touch these
// tasks and says so. Only Chaquopy's own tasks are marked, so the rest of the
// project keeps the cache everywhere it holds today.
tasks.matching { it.javaClass.name.startsWith("com.chaquo.python") }
    .configureEach {
        notCompatibleWithConfigurationCache(
            "Chaquopy 17 starts an external Python process and is not configuration-cache serializable"
        )
    }

// #487 — a RELEASE build must never ship without the E5 model: a missing asset
// is a build failure, not a silent keyword-only APK. `downloadE5Model` is the
// only supported way to produce the assets, and this task is wired into the
// release pipeline so the failure is mechanical instead of invisible.
val verifyE5ModelAssets = tasks.register("verifyE5ModelAssets") {
    group = "verification"
    description = "Fails when a release build lacks the E5 model + tokenizer assets (#487)"
    val modelFile = file("src/main/assets/models/e5/model.onnx")
    val tokenizerFile = file("src/main/assets/models/e5/tokenizer.json")
    inputs.files(modelFile, tokenizerFile).optional()
    doLast {
        val missing = listOf(modelFile, tokenizerFile).filterNot { it.isFile }
        check(missing.isEmpty()) {
            "Release build requires the E5 model assets; run ./gradlew downloadE5Model. Missing: $missing"
        }
    }
}
tasks.matching { it.name == "preReleaseBuild" }.configureEach {
    dependsOn(verifyE5ModelAssets)
}

// #829 — the Telegram MTProto engine (TDLib) as a PINNED prebuilt AAR.
// Maven Central's only artifact is `ca.denisab85:tdlib` 1.8.8 (2022-11-12), so
// the maintained prebuilt release is the source. The AAR is never committed
// (40 MB); the version AND its sha256 are pinned here, and a mismatch fails the
// download instead of silently building against a different binary — the same
// discipline as downloadE5Model.
val downloadTdlib by tasks.registering(Exec::class) {
  group = "verification"
  description = "Downloads the pinned TDLib 1.8.67-d1085f9 AAR (sha256-verified) into app/libs"
  val libsDir = file("libs")
  val aarFile = libsDir.resolve("tdlib-1.8.67-d1085f9.aar")
  doFirst {
    libsDir.mkdirs()
    if (aarFile.exists()) logger.lifecycle("tdlib AAR already present — skipping download")
  }
  commandLine(
    "bash", "-c",
    """
      set -euo pipefail
      mkdir -p "${'$'}(pwd)/libs"
      target="libs/tdlib-1.8.67-d1085f9.aar"
      if [ -f "${'$'}target" ]; then exit 0; fi
      url="https://github.com/FaiBah/TDLibAndroidPrebuilt/releases/download/v1.8.67-d1085f9-Java/tdlib.aar"
      expected="d54097da1ff2d8ed32cbf2dbe42ef4ce59b14d0bb7d4561d267a968d63135c91"
      tmp="${'$'}(mktemp)"
      curl -sL --max-time 1200 -o "${'$'}tmp" "${'$'}url"
      actual="${'$'}(sha256sum "${'$'}tmp" | awk '{print ${'$'}1}')"
      if [ "${'$'}actual" != "${'$'}expected" ]; then
        echo "TDLib AAR sha256 mismatch: got ${'$'}actual, expected ${'$'}expected" >&2
        rm -f "${'$'}tmp"
        exit 1
      fi
      mv "${'$'}tmp" "${'$'}target"
      echo "TDLib AAR verified (${'$'}expected)"
    """.trimIndent()
  )
}

// #829 — the AAR is a compile dependency, so the pinned artifact must exist
// before any build; the download task is the only supported producer.
tasks.named("preBuild") { dependsOn(downloadTdlib) }

// #525: this manual macOS composition target owns one supervised native worker.
// Production startup and the six normal CI partitions keep their own contracts.
val controlledAppCases = mapOf(
  "related-import" to ("com.slukhayka.audiobooks.data.collective.ControlledAttachedAppRelatedCompositionTest" to
    "actual attached App public import persists observed related cards for its public overview reader"),
  "overview-late-room" to ("com.slukhayka.audiobooks.data.collective.ControlledAttachedAppLateRoomOverviewTest" to
    "actual attached App live overview publishes a later same Room block without another refresh"),
  "arrivals-live-feed" to ("com.slukhayka.audiobooks.data.collective.ControlledAttachedAppArrivalsCompositionTest" to
    "actual attached App public live feed persists received arrivals for its public overview reader"),
)
val controlledAppCase = providers.gradleProperty("controlledApp.case").orElse("related-import").get()
val controlledAppSelection = controlledAppCases[controlledAppCase]
  ?: throw GradleException("Unknown controlled App case")
val controlledAppClass = controlledAppSelection.first
val controlledAppMethod = controlledAppSelection.second
val controlledAppPatterns = setOf("$controlledAppClass.$controlledAppMethod", "$controlledAppClass.$controlledAppMethod[36]")
val controlledAppMainClasses = mapOf(
  "related-import" to listOf("com/slukhayka/audiobooks/App.class", "com/slukhayka/audiobooks/data/imports/LibraryImport.class", "com/slukhayka/audiobooks/data/db/AudiobookDao.class", "com/slukhayka/audiobooks/data/db/AudiobookDao_Impl.class", "com/slukhayka/audiobooks/data/imports/LibraryImport\$importBookFromSource\$2.class"),
  "overview-late-room" to listOf("com/slukhayka/audiobooks/App.class", "com/slukhayka/audiobooks/ui/MainViewModel.class", "com/slukhayka/audiobooks/ui/MainViewModel\$refreshCollectiveBlocks\$1.class", "com/slukhayka/audiobooks/ui/MainViewModel\$fillBlockCovers\$1.class", "com/slukhayka/audiobooks/data/db/AudiobookDatabase.class", "com/slukhayka/audiobooks/data/db/AudiobookDao.class", "com/slukhayka/audiobooks/data/db/AudiobookDao_Impl.class", "com/slukhayka/audiobooks/data/collective/CollectiveOverviewBlocks.class", "com/slukhayka/audiobooks/data/collective/RoomCollectiveFeedBlockStore.class", "com/slukhayka/audiobooks/data/collective/RoomCollectiveFeedBlockStore\$activate\$2.class", "com/slukhayka/audiobooks/data/collective/RoomCollectiveFeedBlockStore\$active\$2.class", "com/slukhayka/audiobooks/data/collective/CollectiveFeedBlockCodec.class"),
  "arrivals-live-feed" to listOf("com/slukhayka/audiobooks/App.class", "com/slukhayka/audiobooks/App\$sourceCatalog\$2\$1.class", "com/slukhayka/audiobooks/App\$sourceCatalog\$2\$2.class", "com/slukhayka/audiobooks/App\$observeSourceArrivals\$3.class", "com/slukhayka/audiobooks/data/catalog/SourceCatalog.class", "com/slukhayka/audiobooks/data/catalog/SourceCatalog\$refreshSourceFeeds\$2.class", "com/slukhayka/audiobooks/data/catalog/SourceCatalog\$newFeedFor\$outcome\$1.class", "com/slukhayka/audiobooks/data/catalog/FeedSnapshotRefresh.class", "com/slukhayka/audiobooks/data/catalog/FeedSnapshotStore.class", "com/slukhayka/audiobooks/data/catalog/WorkIndexStore.class", "com/slukhayka/audiobooks/data/catalog/WorkIndexRefresher.class", "com/slukhayka/audiobooks/data/collective/CollectiveFeedRefresh.class", "com/slukhayka/audiobooks/data/collective/CollectiveOverviewBlocks.class", "com/slukhayka/audiobooks/data/collective/RoomCollectiveFeedBlockStore.class", "com/slukhayka/audiobooks/data/collective/RoomCollectiveFeedBlockStore\$activateIfUnchanged\$2.class", "com/slukhayka/audiobooks/data/collective/RoomCollectiveFeedBlockStore\$active\$2.class", "com/slukhayka/audiobooks/data/collective/CollectiveFeedBlockCodec.class", "com/slukhayka/audiobooks/data/source/SluhayuaAdapter.class", "com/slukhayka/audiobooks/data/source/HttpFetcher.class", "com/slukhayka/audiobooks/data/source/SourceRequestGate.class", "com/slukhayka/audiobooks/data/db/AudiobookDatabase.class", "com/slukhayka/audiobooks/data/db/AudiobookDao.class", "com/slukhayka/audiobooks/data/db/AudiobookDao_Impl.class"),
).getValue(controlledAppCase)

val controlledAppRequested = gradle.startParameter.taskNames.any {
  it.substringAfterLast(':') == "testControlledAttachedApp"
}
val controlledRunDirectory = providers.gradleProperty("controlledApp.runDirectory").orNull
fun controlledJson(file: File, value: Any) {
  file.writeText(groovy.json.JsonOutput.prettyPrint(groovy.json.JsonOutput.toJson(value)) + "\n")
}
fun controlledSha(file: File): String = MessageDigest.getInstance("SHA-256")
  .digest(file.readBytes()).joinToString("") { "%02x".format(it.toInt() and 255) }
fun controlledNegativeFirebase() {
  check(file(".").walkTopDown().none { it.name == "google-services.json" }) {
    "Controlled App target requires an unconfigured Firebase fixture; use a separate checkout without google-services.json. No credentials are removed."
  }
  check(file("build/generated").walkTopDown().none { it.name.startsWith("google-services") }) {
    "Generated Firebase resources are present; use a separate unconfigured checkout."
  }
}
fun controlledSupervisor(stage: String = "startup"): File {
  val run = controlledRunDirectory?.let(::File)
    ?: throw GradleException("Use python3 scripts/test-controlled-app.py run; direct controlled dispatch is unsupported")
  val parent = rootProject.layout.buildDirectory.dir("controlled-app").get().asFile
  check(run.isDirectory && !Files.isSymbolicLink(run.toPath())) { "Controlled App $stage supervisor: run directory missing or symbolic link" }
  check(run.canonicalFile == run.absoluteFile && Files.isSameFile(run.parentFile.toPath(), parent.toPath())) { "Controlled App $stage supervisor: run directory is not canonical or parent physical identity differs" }
  val receipt = groovy.json.JsonSlurper().parse(run.resolve("supervisor.json")) as Map<*, *>
  check(Files.isSameFile(File(receipt["root"] as String).toPath(), rootProject.projectDir.toPath())) { "Controlled App $stage supervisor: repository physical identity differs" }
  check(Files.isSameFile(File(receipt["runDirectory"] as String).toPath(), run.toPath())) { "Controlled App $stage supervisor: receipt run directory physical identity differs" }
  check(receipt["case"] == controlledAppCase && receipt["class"] == controlledAppClass && receipt["method"] == controlledAppMethod) { "Controlled App $stage case/class/method differs from owned supervisor" }
  check(receipt["state"] == "one-supervised-gradle-attempt") { "Controlled App $stage supervisor: receipt state is not an active one-shot attempt" }
  check(receipt["token"] == System.getenv("SLUKHAYKA_CONTROLLED_APP_TOKEN")) { "Controlled App $stage supervisor: ownership token does not match" }
  val pid = (receipt["pid"] as Number).toLong()
  val supervisor = ProcessHandle.of(pid).orElseThrow()
  check(supervisor.isAlive) { "Controlled App $stage supervisor: owned process is no longer alive" }
  check(supervisor.info().startInstant().orElseThrow().epochSecond == (receipt["processStartEpochSecond"] as Number).toLong()) { "Controlled App $stage supervisor: process birth identity differs" }
  check(supervisor.info().commandLine().orElseThrow().contains("test-controlled-app.py")) { "Controlled App $stage supervisor: process command identity differs" }
  check(!run.resolve("process-terminal.json").exists() && !run.resolve("receipt.json").exists()) { "Controlled App $stage supervisor: attempt already has terminal or acceptance receipt" }
  check(System.getProperty("os.name").startsWith("Mac")) { "Controlled App pins support macOS only" }
  controlledNegativeFirebase()
  return run
}
if (!controlledAppRequested && gradle.startParameter.taskRequests.flatMap { it.args }.any { it.contains("ControlledAttachedApp") || it.contains("ControlledAppFixtureRunner") }) {
  throw GradleException("Use python3 scripts/test-controlled-app.py run for the controlled App oracle")
}
if ((controlledRunDirectory != null || providers.gradleProperty("controlledApp.case").isPresent) && !controlledAppRequested) {
  throw GradleException("controlledApp.runDirectory is reserved for scripts/test-controlled-app.py run")
}
if (controlledAppRequested) {
  check(gradle.startParameter.taskNames == listOf(":app:validateTestPartitions", ":app:testControlledAttachedApp"))
  check(!providers.gradleProperty("test.selectedClasses").isPresent)
  check(gradle.startParameter.allInitScripts.isEmpty() && gradle.startParameter.excludedTaskNames.isEmpty()) {
    "Controlled target rejects init scripts and excluded tasks; use the supervised helper in a normal clean Gradle environment"
  }
  check(gradle.startParameter.taskRequests.flatMap { it.args } == listOf(":app:validateTestPartitions", ":app:testControlledAttachedApp"))
  check(!gradle.startParameter.isBuildCacheEnabled && !gradle.startParameter.isConfigurationCacheRequested)
  val run = controlledSupervisor()
  check(!run.resolve("gradle-configured.json").exists()) { "One supervised Gradle invocation only" }
  val supervisorReceipt = groovy.json.JsonSlurper().parse(run.resolve("supervisor.json")) as Map<*, *>
  val supervisorProcess = ProcessHandle.of((supervisorReceipt["pid"] as Number).toLong()).orElseThrow()
  check(supervisorProcess.descendants().use { children -> children.anyMatch { it.pid() == ProcessHandle.current().pid() } })
  controlledJson(run.resolve("gradle-configured.json"), mapOf(
    "gradlePID" to ProcessHandle.current().pid(), "supervisorSHA256" to controlledSha(run.resolve("supervisor.json")),
    "tasks" to gradle.startParameter.taskNames, "case" to controlledAppCase, "class" to controlledAppClass, "method" to controlledAppMethod,
  ))
  tasks.named("preBuild") { doFirst { controlledSupervisor() } }
}
val controlledSdk = if (controlledAppRequested) configurations.create("controlledAppRobolectricSdk") {
  isCanBeConsumed = false
  isCanBeResolved = true
  isTransitive = false
} else null
if (controlledSdk != null) dependencies.add(controlledSdk.name,
  "org.robolectric:android-all-instrumented:16-robolectric-13921718-i7")

// Gradle task abbreviations must not turn a direct manual alias into an
// unrestricted base Test run before the missing supervisor is detected.
gradle.taskGraph.whenReady {
  if (hasTask(":app:testControlledAttachedApp") && !controlledAppRequested) {
    throw GradleException("Use python3 scripts/test-controlled-app.py run; controlled task abbreviations/dependency aliases are unsupported")
  }
  if (controlledAppRequested) {
    check(hasTask(":app:testControlledAttachedApp")) { "Controlled App compiler configuration requires the selected controlled target" }
    val compiler = allTasks.singleOrNull { it.path == ":app:compileDebugUnitTestKotlin" }
      ?: throw GradleException("Controlled App requires exactly one selected compileDebugUnitTestKotlin task")
    val mainCompiler = allTasks.singleOrNull { it.path == ":app:compileDebugKotlin" }
      ?: throw GradleException("Controlled App requires exactly one selected main compiler")
    check(mainCompiler is org.jetbrains.kotlin.gradle.tasks.KotlinCompileTool)
    val baselineRun = controlledSupervisor("main-baseline")
    check(!baselineRun.resolve("main-class-baseline.json").exists()) { "One actual main baseline only" }
    val mainOutput = mainCompiler.destinationDirectory.get().asFile
    controlledJson(baselineRun.resolve("main-class-baseline.json"), mapOf(
      "case" to controlledAppCase, "class" to controlledAppClass, "method" to controlledAppMethod,
      "task" to mainCompiler.path, "timeMillis" to System.currentTimeMillis(),
      "destinationDirectory" to mainOutput.canonicalPath,
      "classes" to controlledAppMainClasses.map { name ->
        val file = mainOutput.resolve(name)
        mapOf("class" to name, "exists" to file.isFile,
          "SHA256" to if (file.isFile) controlledSha(file) else null,
          "mtimeMillis" to if (file.isFile) file.lastModified() else null)
      },
    ))
    // The graph contains realized tasks; configure this compiler before execution and input snapshots.
    compiler.apply {
      check(this is org.jetbrains.kotlin.gradle.tasks.KotlinCompileTool)
      check(this is org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile<*>)
      val compile = this as org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile<*>
      val tool = this as org.jetbrains.kotlin.gradle.tasks.KotlinCompileTool
      compile.incremental = false
      outputs.upToDateWhen { false }
      outputs.cacheIf { false }
      doFirst {
        val run = controlledSupervisor("precompile")
        check(!run.resolve("compile-start.json").exists()) { "One actual targeted compile only" }
        check(!compile.incremental) { "Controlled App precompile requires incremental=false after selected-task configuration" }
        controlledJson(run.resolve("compile-start.json"), mapOf(
          "task" to path, "timeMillis" to System.currentTimeMillis(), "incremental" to false,
          "case" to controlledAppCase, "class" to controlledAppClass, "method" to controlledAppMethod,
          "actualTaskClass" to javaClass.name,
          "compilerCodeSource" to org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile::class.java.protectionDomain.codeSource.location.toString(),
          "compilerCodeSourceSHA256" to controlledSha(File(org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile::class.java.protectionDomain.codeSource.location.toURI())),
          "destinationDirectory" to tool.destinationDirectory.get().asFile.canonicalPath,
        ))
      }
      doLast {
        val run = controlledSupervisor()
        val output = tool.destinationDirectory.get().asFile
        val classes = listOf(controlledAppClass.substringAfterLast('.'), "ControlledAppFixtureRunner").map { name ->
          val file = output.resolve("com/slukhayka/audiobooks/data/collective/$name.class")
          check(file.isFile)
          mapOf("path" to file.canonicalPath, "SHA256" to controlledSha(file), "mtimeMillis" to file.lastModified())
        }
        controlledJson(run.resolve("compile-end.json"), mapOf(
          "task" to path, "timeMillis" to System.currentTimeMillis(), "classes" to classes,
          "case" to controlledAppCase, "class" to controlledAppClass, "method" to controlledAppMethod,
        ))
      }
    }
  }
}
tasks.register("testControlledAttachedApp") {
  group = "verification"
  description = "Runs the manually supervised, provider-free attached App composition on macOS."
  dependsOn("testDebugUnitTest")
  doFirst { controlledSupervisor() }
}
androidComponents.onVariants(androidComponents.selector().withBuildType("debug")) { variant ->
  (variant as HasUnitTest).unitTest?.configureTestTask { test: GradleTest ->
    if (!controlledAppRequested) {
      // The explicit composition fixture never enters an unrestricted/default CI worker.
      controlledAppCases.values.forEach { test.filter.excludeTestsMatching(it.first) }
    } else {
      test.workingDir = projectDir
      test.maxParallelForks = 1
      test.forkEvery = 1
      test.outputs.upToDateWhen { false }
      test.outputs.cacheIf { false }
      test.setIncludes(emptyList<String>())
      test.setExcludes(emptyList<String>())
      test.filter.setIncludePatterns(*controlledAppPatterns.toTypedArray())
      test.filter.setExcludePatterns()
      test.filter.isFailOnNoMatchingTests = true
      test.systemProperty("robolectric.installFakeMediaProvider", "false")
      test.doFirst {
        val run = controlledSupervisor()
        check(!run.resolve("runtime-input.json").exists()) { "One controlled dispatch only" }
        check(test.filter.includePatterns == controlledAppPatterns && test.filter.excludePatterns.isEmpty())
        check(test.includes.isEmpty() && test.excludes.isEmpty())
        check(test.maxParallelForks == 1 && test.forkEvery == 1L && test.workingDir.canonicalFile == projectDir.canonicalFile)
        val task = tasks.named("compileDebugUnitTestKotlin").get()
        check(task is org.jetbrains.kotlin.gradle.tasks.KotlinCompileTool)
        val main = tasks.named("compileDebugKotlin").get()
        check(main is org.jetbrains.kotlin.gradle.tasks.KotlinCompileTool)
        val classpath = test.classpath.files.toList()
        // Capture public producer outputs and completed state, not guessed optional paths.
        val dependencyRoots = test.classpath.buildDependencies.getDependencies(test).sortedBy { it.path }
        val dependencyTasks = mutableMapOf<String, org.gradle.api.Task>()
        val dependencyEdges = mutableSetOf<Pair<String, String>>()
        val pendingDependencies = dependencyRoots.toMutableList()
        while (pendingDependencies.isNotEmpty()) {
          val dependency = pendingDependencies.removeAt(0)
          if (dependencyTasks.putIfAbsent(dependency.path, dependency) == null) {
            dependency.taskDependencies.getDependencies(dependency).sortedBy { it.path }.forEach { child ->
              dependencyEdges.add(dependency.path to child.path)
              pendingDependencies.add(child)
            }
          }
        }
        val selectedTasks = gradle.taskGraph.allTasks.associateBy { it.path }
        val producerPaths = listOf(":app:kspDebugUnitTestKotlin", ":app:compileDebugUnitTestJavaWithJavac")
        val producers = producerPaths.map { path ->
          val producer = selectedTasks[path] ?: error("Controlled output producer is not selected: $path")
          check(dependencyTasks[path] === producer) { "Producer has no actual Test classpath dependency witness: $path" }
          val state = producer.state
          check(state.executed && state.failure == null) { "Controlled output producer did not complete successfully: $path" }
          val record = mutableMapOf<String, Any?>(
            "task" to path, "selected" to true, "className" to producer.javaClass.name,
            "outputs" to producer.outputs.files.files.map { it.canonicalPath }.sorted(),
            "state" to mapOf("executed" to state.executed, "didWork" to state.didWork,
              "upToDate" to state.upToDate, "noSource" to state.noSource,
              "skipped" to state.skipped, "skipMessage" to state.skipMessage,
              "hasFailure" to (state.failure != null)),
          )
          if (path == ":app:compileDebugUnitTestJavaWithJavac") {
            check(producer is org.gradle.api.tasks.compile.JavaCompile) { "Actual Java output producer must be public JavaCompile" }
            record["destinationDirectory"] = producer.destinationDirectory.get().asFile.canonicalPath
            record["sourceFiles"] = producer.source.files.map { it.canonicalPath }.sorted()
            record["sourceEmpty"] = producer.source.files.isEmpty()
          }
          record
        }
        val buildDirectory = layout.buildDirectory.get().asFile.canonicalFile
        val javaDestination = producers.single { it["task"] == ":app:compileDebugUnitTestJavaWithJavac" }["destinationDirectory"]
        val outputProvenance = mapOf(
          "gradleVersion" to gradle.gradleVersion, "selectedTestTask" to test.path,
          "projectBuildDirectory" to buildDirectory.canonicalPath,
          "classpathBuildDependencyRoots" to dependencyRoots.map { it.path },
          "dependencyEdges" to dependencyEdges.sortedWith(compareBy({ it.first }, { it.second })).map { listOf(it.first, it.second) },
          "producers" to producers,
          "optionalOutputs" to listOf(
            mapOf("path" to buildDirectory.resolve("generated/ksp/debugUnitTest/resources").canonicalPath,
              "producerTask" to ":app:kspDebugUnitTestKotlin", "role" to "ksp-resources"),
            mapOf("path" to buildDirectory.resolve("generated/ksp/debugUnitTest/classes").canonicalPath,
              "producerTask" to ":app:kspDebugUnitTestKotlin", "role" to "ksp-classes"),
            mapOf("path" to javaDestination, "producerTask" to ":app:compileDebugUnitTestJavaWithJavac", "role" to "java-classes"),
          ),
        )
        val configEntry = "com/android/tools/test_config.properties"
        val definitions = classpath.mapNotNull { entry ->
          if (entry.isDirectory) {
            val member = entry.resolve(configEntry)
            if (member.isFile) entry to member.readBytes() else null
          } else if (entry.extension == "jar") {
            ZipFile(entry).use { zip -> zip.getEntry(configEntry)?.let { entry to zip.getInputStream(it).use { stream -> stream.readBytes() } } }
          } else null
        }
        check(definitions.size == 1) { "Exactly one actual Test classpath test_config.properties is required" }
        val properties = Properties().apply {
          definitions.single().second.inputStream().reader(Charsets.UTF_8).use { load(it) }
        }
        val original = File(properties.getProperty("android_resource_apk") ?: error("android_resource_apk missing"))
          .let { if (it.isAbsolute) it else File(test.workingDir, it.path) }.canonicalFile
        val sdkFile = controlledSdk!!.singleFile
        check(sdkFile.name == "android-all-instrumented-16-robolectric-13921718-i7.jar")
        controlledJson(run.resolve("runtime-input.json"), mapOf(
          "case" to controlledAppCase, "class" to controlledAppClass, "method" to controlledAppMethod,
          "timeMillis" to System.currentTimeMillis(),
          "mainCompilerState" to mapOf("task" to main.path, "executed" to main.state.executed,
            "upToDate" to main.state.upToDate, "didWork" to main.state.didWork, "hasFailure" to (main.state.failure != null)),
          "task" to test.path, "workingDirectory" to test.workingDir.canonicalPath,
          "classpath" to classpath.map { it.canonicalPath },
          "classpathOutputProvenance" to outputProvenance,
          "testConfigOrigin" to definitions.single().first.canonicalPath,
          "testConfigSHA256" to MessageDigest.getInstance("SHA-256").digest(definitions.single().second).joinToString("") { "%02x".format(it.toInt() and 255) },
          "originalApk" to original.canonicalPath,
          "sdkDirectory" to androidComponents.sdkComponents.sdkDirectory.get().asFile.canonicalPath,
          "robolectricSdk" to sdkFile.canonicalPath,
          "unitDestinationDirectory" to task.destinationDirectory.get().asFile.canonicalPath,
          "mainDestinationDirectory" to main.destinationDirectory.get().asFile.canonicalPath,
          "runtimeSourceClaims" to "actual ordered Test.classpath and public compiler destinationDirectory",
        ))
        val log = run.resolve("pre-worker-packager.log")
        val packager = ProcessBuilder("python3", rootProject.file("scripts/test-controlled-app.py").absolutePath,
          "package", "--run-directory", run.canonicalPath).directory(rootProject.projectDir)
          .redirectErrorStream(true).redirectOutput(log).start()
        if (!packager.waitFor(90, TimeUnit.SECONDS)) {
          packager.destroy()
          if (!packager.waitFor(5, TimeUnit.SECONDS)) packager.destroyForcibly()
          throw GradleException("Controlled packager exceeded 90 seconds; see ${log.path}")
        }
        check(packager.exitValue() == 0) { "Controlled pre-worker gate failed; see ${log.path}" }
        controlledNegativeFirebase()
        val gate = run.resolve("fixture/fixture.properties")
        test.systemProperty("slukhayka.s2.fixtureGate", gate.canonicalPath)
        test.systemProperty("slukhayka.s2.fixtureGateSHA256", controlledSha(gate))
        test.systemProperty("robolectric.dependency.dir", sdkFile.parentFile.canonicalPath)
        test.systemProperty("robolectric.offline", "true")
      }
    }
  }
}
