import com.android.build.api.artifact.SingleArtifact
import com.android.build.api.variant.BuiltArtifactsLoader
import com.google.gms.googleservices.GoogleServicesPlugin.MissingGoogleServicesStrategy
import java.io.File
import java.util.Properties
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.register

plugins {
  alias(libs.plugins.android.application)
  alias(libs.plugins.kotlin.compose)
  alias(libs.plugins.google.devtools.ksp)
  alias(libs.plugins.roborazzi)
  alias(libs.plugins.secrets)
  alias(libs.plugins.google.services)
  alias(libs.plugins.firebase.crashlytics)
  alias(libs.plugins.kover)
}

fun intProperty(name: String): Int? = providers.gradleProperty(name).orNull?.toIntOrNull()

kover {
  reports {
    total {
      html { onCheck = false }
      xml { onCheck = true }
      verify {
        rule {
          minBound(intProperty("kover.instructionThreshold") ?: 80)
        }
        rule {
          minBound(intProperty("kover.branchThreshold") ?: 70, coverageUnits = kotlinx.kover.gradle.plugin.dsl.CoverageUnit.BRANCH)
        }
      }
    }
  }
}

// wayfinder #47: export Room schemas into the repo so future migrations are
// reviewable and verifiable. KSP writes the JSON for the current database
// version on every build.
ksp {
  arg("room.schemaLocation", "$projectDir/schemas")
}

android {
  namespace = "com.slukhayka.audiobooks"
  compileSdk { version = release(36) { minorApiLevel = 1 } }

  defaultConfig {
    applicationId = "com.slukhayka.audiobooks"
    minSdk = 24
    targetSdk = 36
    // spec-29 T1 (#210): first release under the permanent applicationId.
    // versionCode grows monotonically across the Слухайка line (v1.0 was 1).
    versionCode = 7
    versionName = "1.3.7"

    testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
  }

  signingConfigs {
    create("release") {
      // CI (release.yml) passes KEYSTORE_PATH/STORE_PASSWORD/KEY_PASSWORD as
      // env vars — those win. Locally we fall back to a gitignored
      // keystore.properties (generated by scripts/generate-keystore.sh), so
      // `./gradlew :app:assembleRelease` works with no env setup.
      val propsFile = rootProject.file("keystore.properties")
      val props = Properties().apply {
        if (propsFile.exists()) propsFile.inputStream().use { load(it) }
      }
      val keystorePath = System.getenv("KEYSTORE_PATH")
        ?: props.getProperty("keystorePath")
        ?: "my-upload-key.jks"
      // Resolve relative paths against the repo root (the signing config
      // lives in the :app module, whose own dir is app/).
      storeFile = rootProject.file(keystorePath)
      storePassword = System.getenv("STORE_PASSWORD") ?: props.getProperty("storePassword")
      keyAlias = System.getenv("KEY_ALIAS") ?: props.getProperty("keyAlias") ?: "upload"
      keyPassword = System.getenv("KEY_PASSWORD") ?: props.getProperty("keyPassword")
    }
  }

  buildTypes {
    debug {
      // Install developer builds next to the signed release app so on-device
      // testing never requires uninstalling (and losing) the listener's data.
      applicationIdSuffix = ".debug"
    }
    release {
      isCrunchPngs = false
      isMinifyEnabled = false
      proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
      signingConfig = signingConfigs.getByName("release")
    }
    // Debug uses AGP's default debug signing (auto-generated ~/.android/debug.keystore).
    // A custom signingConfig pointing at a gitignored ${rootDir}/debug.keystore was
    // removed — it broke every fresh checkout and CI run at :app:validateSigningDebug.
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
  }
  buildFeatures {
    compose = true
    buildConfig = true
  }
  testOptions { unitTests { isIncludeAndroidResources = true } }
}

// spec-29 T1 (#210): the release artifact carries the version in its name
// (slukhayka-v1.1.apk, v1.2, v1.3, ...) so downloads are unambiguous across
// releases (US-13). AGP 9 removed the old outputFileName hook, so this reacts
// to SingleArtifact.APK creation with the public Variant API (the documented
// listenToArtifacts replacement) and copies the built APK to the versioned
// name under app/build/outputs/renamed_apks/release/. The name comes from the
// APK's own metadata (BuiltArtifact.versionName), so it can never drift from
// what is actually inside the file. Debug keeps its AGP default name.
androidComponents {
  onVariants(selector().withBuildType("release")) { variant ->
    val renameTask = tasks.register<RenameReleaseApk>("renameReleaseApk") {
      output.set(layout.buildDirectory.dir("outputs/renamed_apks/release"))
      builtArtifactsLoader.set(variant.artifacts.getBuiltArtifactsLoader())
    }
    variant.artifacts.use(renameTask).wiredWith { it.input }.toListenTo(SingleArtifact.APK)
  }
}

// Copies the built release APK to slukhayka-v<versionName>.apk. The input is
// the directory AGP publishes for SingleArtifact.APK; the loader enumerates
// the APKs inside it with their metadata (single APK in our case — no splits).
abstract class RenameReleaseApk : DefaultTask() {
  @get:InputDirectory
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract val input: DirectoryProperty

  @get:OutputDirectory
  abstract val output: DirectoryProperty

  @get:Internal
  abstract val builtArtifactsLoader: Property<BuiltArtifactsLoader>

  @TaskAction
  fun rename() {
    val builtArtifacts = builtArtifactsLoader.get().load(input.get())
      ?: throw GradleException("Cannot load built APKs from ${input.get()}")
    builtArtifacts.elements.forEach { artifact ->
      val targetName = "slukhayka-v${artifact.versionName}.apk"
      File(artifact.outputFile).copyTo(output.get().file(targetName).asFile, overwrite = true)
    }
  }
}

// Configure the Secrets Gradle Plugin to use .env and .env.example files
// to match the convention used in Web projects.
secrets {
  propertiesFileName = ".env"
  defaultPropertiesFileName = ".env.example"
}

googleServices { missingGoogleServicesStrategy = MissingGoogleServicesStrategy.WARN }

// Some unused dependencies are commented out below instead of being removed.
// This makes it easy to add them back in the future if needed.
dependencies {
  // Spec 2026-08-26: ONE protobuf runtime in the APK — protobuf-javalite
  // 3.25.5, the version Firestore's protolite codegen pairs with and the
  // version the JVM probe verified NewPipeExtractor extracts fully on.
  // Three artifacts were fighting over com.google.protobuf classes —
  // Firebase's protolite (old, stripped: NewPipe died invisibly on its
  // missing InvalidProtocolBufferException), NewPipe's javalite 4.35.1, and
  // Firestore's transitive javalite 3.25.1 — and the APK build refuses
  // duplicates. protolite is excluded entirely; its NON-protobuf half (the
  // googleapis common protos Firestore decodes — com.google.type.LatLng et
  // al., without which GeoPoint/WriteBatch crash) ships as the surgical
  // app/libs/protolite-googleapis.jar with com/google/protobuf stripped.
  configurations.all {
    exclude(group = "com.google.firebase", module = "protolite-well-known-types")
    resolutionStrategy {
      force("com.google.protobuf:protobuf-javalite:3.25.5")
    }
  }
  implementation(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"))))
  implementation(platform(libs.androidx.compose.bom))
  implementation(platform(libs.firebase.bom))
  // implementation(libs.accompanist.permissions)
  implementation(libs.androidx.activity.compose)
  // implementation(libs.androidx.camera.camera2)
  // implementation(libs.androidx.camera.core)
  // implementation(libs.androidx.camera.lifecycle)
  // implementation(libs.androidx.camera.view)
  implementation(libs.androidx.compose.material.icons.core)
  implementation(libs.androidx.compose.material.icons.extended)
  implementation(libs.androidx.compose.material3)
  implementation(libs.androidx.compose.ui)
  implementation(libs.androidx.compose.ui.graphics)
  implementation(libs.androidx.compose.ui.tooling.preview)
  implementation(libs.androidx.core.ktx)
  implementation(libs.androidx.documentfile)
  implementation(libs.androidx.glance.appwidget)
  implementation(libs.androidx.glance.material3)
  // Spec-38 T3 (#255): the official webkit controller rides the privacy route
  // (ProxyController) and the document-start sensor lockdown (WebViewCompat).
  implementation(libs.androidx.webkit)
  // Spec-40 #276 (t2): the BiometricPrompt gate for «Код відновлення профілю».
  implementation(libs.androidx.biometric)
  implementation(libs.androidx.media3.exoplayer)
  implementation(libs.androidx.media3.session)
  // ADR-0024: CastPlayer swaps in behind the MediaSession player seam while
  // casting; the receiver itself never touches the network (phone proxy).
  implementation(libs.androidx.media3.cast)
  implementation(libs.play.services.cast.framework)
  implementation(libs.nanohttpd)
  // implementation(libs.androidx.datastore.preferences)
  implementation(libs.androidx.lifecycle.runtime.compose)
  implementation(libs.androidx.lifecycle.runtime.ktx)
  implementation(libs.androidx.lifecycle.viewmodel.compose)
  implementation(libs.androidx.navigation.compose)
  // Spec-23 T4: the endless merged catalogue feed (Paging 3).
  implementation(libs.androidx.paging.runtime)
  implementation(libs.androidx.paging.compose)
  implementation(libs.androidx.room.ktx)
  implementation(libs.androidx.room.runtime)
  // Room's PagingSource DAO support (spec-23 T4 endless feed).
  implementation(libs.androidx.room.paging)
  implementation(libs.coil.compose)
  implementation(libs.converter.moshi)
  implementation(libs.firebase.ai)
  // Spec-26 T5: the shared universe-knowledge base (Firestore free tier).
  // Requires a local (gitignored) google-services.json — without it the
  // shared layer is simply absent and the app works as before.
  // Spec-40 #275 (t1): the silent listener identity — Anonymous Auth
  // immediately elevated with generated credentials. Without Firebase keys
  // the identity degrades to the local-only profile.
  implementation(libs.firebase.auth)
  implementation(libs.firebase.crashlytics)
  implementation(libs.firebase.appcheck.recaptcha)
  implementation(libs.kotlinx.coroutines.android)
  implementation(libs.kotlinx.coroutines.core)
  // spec-26 T1 (#175): on-device title translation for the Wikidata search
  // fallback — free, no API key, models download once per language pair.
  implementation(libs.mlkit.translate)
  implementation(libs.logging.interceptor)
  implementation(libs.moshi.kotlin)
  implementation(libs.okhttp)
  // Spec 2026-08-26: YouTube stream extraction for audio-less 4read pages —
  // the watch URL resolves to a progressive audio stream at play/download
  // time. Distribution is JitPack; rhino (deobfuscation) needs keep rules
  // under minification (see proguard-rules.pro).
  implementation("com.github.teamnewpipe:NewPipeExtractor:v0.26.5")
  implementation(libs.firebase.firestore)

  // spec-38 T4 (#256): the RFC-8484 DoH resolver behind the privacy door —
  // same OkHttp version, one small artifact.
  implementation(libs.okhttp.dnsoverhttps)
  // Spec #361 («Проксі відтворення»): the embedded HTTP server inside the
  // playback proxy — plain sockets on one jar, no other surface.
  implementation(libs.nanohttpd)
  // implementation(libs.play.services.location)
  implementation(libs.retrofit)
  // spec-19 T3: on-device ONNX inference for the recommendation embedder
  // (ai.onnxruntime API). The Android artifact ships the model runner into
  // the app. The desktop (JVM) artifact is deliberately NOT a test
  // dependency — both jars contain the same ai.onnxruntime classes, so a
  // duplicate on the unit-test classpath would be ambiguous. The eval gate
  // script gets the desktop jar via its own configuration below.
  implementation(libs.onnxruntime.android)

// spec-19 T3: the reproducible eval gate — runRecommendationEval. A host
// JVM script (test sources, so it reuses the fixtures + RecommendationEval)
// that loads the downloaded ONNX model and prints recall@20/NDCG@20 for
// baseline vs semantic, writing the report. The desktop onnxruntime jar
// (with host natives) comes only from this configuration; the android AAR
// is filtered out of the script's classpath.
val evalRuntime: Configuration by configurations.creating

dependencies {
  add("evalRuntime", libs.onnxruntime.jvm)
}

// spec-19 T3: fetches the ONNX model (int8 multilingual-e5-small, ~118 MB)
// into app/src/main/assets/models/e5/. Not committed (GitHub's 100 MB
// file limit); the embedder degrades to the keyword baseline when absent.
val downloadE5Model by tasks.registering(Exec::class) {
  group = "verification"
  description = "Downloads the multilingual-e5-small int8 ONNX model + tokenizer into app/src/main/assets/models/e5"
  val assetsDir = file("src/main/assets/models/e5")
  val modelFile = assetsDir.resolve("model.onnx")
  doFirst {
    assetsDir.mkdirs()
    if (modelFile.exists()) {
      logger.lifecycle("model.onnx already present — skipping download")
    } else {
      logger.lifecycle("downloading multilingual-e5-small int8 ONNX (~118 MB)...")
    }
  }
  commandLine(
    "bash", "-c",
    """
      set -e
      mkdir -p "${'$'}(pwd)/src/main/assets/models/e5"
      if [ ! -f src/main/assets/models/e5/model.onnx ]; then
        curl -sL --max-time 1200 -o src/main/assets/models/e5/model.onnx \
          "https://huggingface.co/Xenova/multilingual-e5-small/resolve/main/onnx/model_quantized.onnx"
      fi
      if [ ! -f src/main/assets/models/e5/tokenizer.json ]; then
        curl -sL --max-time 120 -o src/main/assets/models/e5/tokenizer.json \
          "https://huggingface.co/Xenova/multilingual-e5-small/resolve/main/tokenizer.json"
      fi
    """.trimIndent()
  )
}

// spec-26 T4: the residual-measurement gate — runUniverseResidualEval. A
// host JVM script (test sources, reusing the catalog fixture) that runs the
// fixed Wikidata provider against the live API with the real transport and
// classifies the misses by cause, writing the report. ML Kit (T1) is
// device-only, so the harness runs without the translator and says so.
val runUniverseResidualEval by tasks.registering(JavaExec::class) {
  group = "verification"
  description = "Runs the spec-26 T4 residual measurement over the catalog sample with the live Wikidata API; writes the report. Overrides via --args=\"path delayMs limit\"."
  mainClass.set("com.slukhayka.audiobooks.data.universe.RunUniverseResidualEval")
  dependsOn("compileDebugUnitTestKotlin", "processDebugUnitTestJavaRes")
  val compileTask = project.tasks.named("compileDebugUnitTestKotlin")
  val testOutput = (compileTask.get() as org.jetbrains.kotlin.gradle.tasks.KotlinCompile).destinationDirectory
  val resourcesOutput = project.layout.buildDirectory.dir("intermediates/java_res/debugUnitTest/processDebugUnitTestJavaRes/out")
  val testCp = project.configurations.getByName("debugUnitTestRuntimeClasspath")
  classpath = project.files(
    testOutput,
    resourcesOutput
  ) + project.files(testCp)
  args("${projectDir}/docs/specs/2026-08-16-universe-residual-report.md")
  isIgnoreExitValue = false
}

val runRecommendationEval by tasks.registering(JavaExec::class) {
  group = "verification"
  description = "Runs the spec-19 leave-one-out eval gate on saved fixtures with the real ONNX model; prints recall@20 / NDCG@20 and the GO/NO-GO decision."
  mainClass.set("com.slukhayka.audiobooks.data.recommend.RunRecommendationEval")
  // Classpath: test+main outputs, the desktop onnxruntime jar, and the
  // test runtime minus the android AAR (whose ai.onnxruntime classes share
  // the package — the desktop jar must win so its host natives load).
  // Compile the unit tests first (RunRecommendationEval lives in test
  // sources); its output dir carries the main class. The android onnxruntime
  // AAR is excluded from the runtime classpath so the desktop jar (with
  // host natives) resolves the ai.onnxruntime API.
  dependsOn("compileDebugKotlin", "compileDebugUnitTestKotlin", "processDebugUnitTestJavaRes")
  val mainCompileTask = project.tasks.named("compileDebugKotlin")
  val mainOutput = (mainCompileTask.get() as org.jetbrains.kotlin.gradle.tasks.KotlinCompile).destinationDirectory
  val compileTask = project.tasks.named("compileDebugUnitTestKotlin")
  val testOutput = (compileTask.get() as org.jetbrains.kotlin.gradle.tasks.KotlinCompile).destinationDirectory
  val resourcesOutput = project.layout.buildDirectory.dir("intermediates/java_res/debugUnitTest/processDebugUnitTestJavaRes/out")
  val testCp = project.configurations.getByName("debugUnitTestRuntimeClasspath")
    .files.filter { !it.name.contains("onnxruntime-android") }
  classpath = project.files(
    project.configurations.getByName("evalRuntime"),
    mainOutput,
    testOutput,
    resourcesOutput
  ) + project.files(testCp)
  // The model+tokenizer assets live under app/src/main/assets/models/e5;
  // the script resolves them relative to the project dir.
  args("${projectDir}/src/main/assets/models/e5")
  isIgnoreExitValue = false
}
  testImplementation(platform(libs.androidx.compose.bom))
  testImplementation(libs.androidx.compose.ui.test.junit4)
  testImplementation(libs.androidx.core)
  testImplementation(libs.androidx.junit)
  testImplementation(libs.junit)
  testImplementation(libs.kotlinx.coroutines.test)
  testImplementation(libs.robolectric)
  testImplementation(libs.roborazzi)
  testImplementation(libs.roborazzi.compose)
  testImplementation(libs.roborazzi.junit.rule)
  androidTestImplementation(platform(libs.androidx.compose.bom))
  androidTestImplementation(libs.androidx.compose.ui.test.junit4)
  androidTestImplementation(libs.androidx.compose.ui.test.junit4.accessibility)
  androidTestImplementation(libs.androidx.compose.ui.test.manifest)
  androidTestImplementation(libs.androidx.core)
  androidTestImplementation(libs.androidx.espresso.core)
  androidTestImplementation(libs.androidx.junit)
  androidTestImplementation(libs.androidx.runner)
  androidTestImplementation(libs.androidx.test.rules)
  androidTestImplementation(libs.kotlinx.coroutines.core)
  debugImplementation(libs.androidx.compose.ui.test.manifest)
  debugImplementation(libs.androidx.compose.ui.tooling)
  "ksp"(libs.androidx.room.compiler)
  "ksp"(libs.moshi.kotlin.codegen)
}

// Compose/Robolectric accessibility suites retain large rendered graphs.
// Keep the CI test worker from exhausting Gradle's default heap mid-suite.
tasks.withType<org.gradle.api.tasks.testing.Test>().configureEach {
  maxHeapSize = "2g"
}

// #423: one source of truth classifies every JVM test into exactly one public
// verification partition. Gradle and the local changed-test selector both
// consume this CLI, so a new test cannot silently disappear between them.
fun partitionTestClasses(
  partition: String,
  cohort: String = "all",
): List<String> {
  val arguments = mutableListOf(
    rootProject.file("scripts/test_partitions.py").absolutePath,
    "--root",
    rootProject.projectDir.absolutePath,
    "list",
    "--partition",
    partition,
    "--cohort",
    cohort,
  )
  return providers.exec {
    workingDir(rootProject.projectDir)
    commandLine("python3", *arguments.toTypedArray())
  }.standardOutput.asText.get().lineSequence().filter(String::isNotBlank).toList()
}

val pureJvmClasses = partitionTestClasses("pure-jvm")
val roomRobolectricClasses = partitionTestClasses("room-robolectric")
val roomNativeSdk35Classes = partitionTestClasses("room-robolectric", "native-sdk35")
val roomNativeSdk36Classes = partitionTestClasses("room-robolectric", "native-sdk36")
val roomNativeDefaultClasses = partitionTestClasses("room-robolectric", "native-default")
val roomRobolectricOnlyClasses = partitionTestClasses("room-robolectric", "non-native")
val composeRoborazziClasses = partitionTestClasses("compose-roborazzi")

// These aliases reuse AGP's standard Test task. Kover 0.9.9 instruments that
// task and emits one portable testDebugUnitTest.ic report in each CI job.
val partitionAliases = mapOf(
  "testPureJvm" to pureJvmClasses,
  "testRoomRobolectric" to roomRobolectricClasses,
  "testRoomNativeSdk35" to roomNativeSdk35Classes,
  "testRoomNativeSdk36" to roomNativeSdk36Classes,
  "testRoomNativeDefault" to roomNativeDefaultClasses,
  "testRoomRobolectricOnly" to roomRobolectricOnlyClasses,
  "testComposeRoborazzi" to composeRoborazziClasses,
)
val requestedPartitionAliases = gradle.startParameter.taskNames
  .map { it.substringAfterLast(':') }
  .filter(partitionAliases::containsKey)
  .distinct()
if (requestedPartitionAliases.size > 1) {
  throw GradleException("Run JVM test partitions separately, or use scripts/test-all.sh")
}

afterEvaluate {
  val baseJvmTest = tasks.named<org.gradle.api.tasks.testing.Test>("testDebugUnitTest")
  partitionAliases.forEach { (alias, _) ->
    tasks.register(alias) {
      group = "verification"
      description = when (alias) {
        "testPureJvm" -> "Runs pure JVM tests without Robolectric."
        "testRoomRobolectric" -> "Runs Room and other non-snapshot Robolectric tests."
        "testRoomNativeSdk35" -> "Runs the isolated SDK 35 native Room cohort."
        "testRoomNativeSdk36" -> "Runs the isolated SDK 36 native Room cohort."
        "testRoomNativeDefault" -> "Runs the isolated default-SDK native Room cohort."
        "testRoomRobolectricOnly" -> "Runs Robolectric tests that do not load native Room."
        else -> "Runs Compose and Roborazzi snapshot tests."
      }
      dependsOn(baseJvmTest)
    }
  }
  requestedPartitionAliases.singleOrNull()?.let { requestedAlias ->
    val selectedClasses = providers.gradleProperty("test.selectedClasses").orNull
      ?.split(',')
      ?.filter(String::isNotBlank)
      ?: partitionAliases.getValue(requestedAlias)
    baseJvmTest.configure {
      systemProperty("slukhayka.test.workerCohort", requestedAlias)
      if (requestedAlias == "testRoomRobolectric") {
        // A fresh fork per class is intentionally stronger than grouping by
        // today's SDK list: future SDK/native SQLite combinations are isolated
        // automatically, without another hard-coded cohort table.
        maxParallelForks = 1
        forkEvery = 1
      } else if (requestedAlias.startsWith("testRoomNative")) {
        // Native SQLite keeps process-wide state even inside one Robolectric
        // SDK cohort. Reuse can therefore contaminate the next Room class.
        // Two fresh workers at a time retain isolation without serializing the
        // entire SDK 36 cohort.
        maxParallelForks = 2
        forkEvery = 1
      } else {
        if (requestedAlias == "testPureJvm") {
          // Pure JVM tests do not initialise Android/Robolectric or native
          // SQLite state, so they can safely use the otherwise idle cores.
          // Cap the fan-out to keep local builds responsive and avoid making
          // CI workers contend for memory.
          maxParallelForks = minOf(4, Runtime.getRuntime().availableProcessors())
        } else {
          maxParallelForks = 1
        }
        if (requestedAlias == "testRoomRobolectricOnly") {
          // Robolectric keeps Android framework state for the life of a test
          // JVM. A fresh worker per class prevents that state from accumulating
          // across the long non-native accessibility suite.
          forkEvery = 1
        }
      }
      if (requestedAlias.startsWith("testRoomNative")) {
        systemProperty(
          "slukhayka.test.workerIdentityFile",
          layout.buildDirectory.file("test-worker-identities.tsv").get().asFile.absolutePath,
        )
      }
      filter {
        isFailOnNoMatchingTests = true
        selectedClasses.forEach(::includeTestsMatching)
      }
    }
  }
}

tasks.register<Exec>("validateTestPartitions") {
  group = "verification"
  description = "Checks that every JVM test belongs to exactly one test partition."
  workingDir(rootProject.projectDir)
  commandLine(
    "python3",
    rootProject.file("scripts/test_partitions.py").absolutePath,
    "--root",
    rootProject.projectDir.absolutePath,
    "validate",
  )
}

// A coverage aggregation job downloads the partition IC files here and
// skips testDebugUnitTest while generating reports. Local Kover use continues
// to run the standard full test task as before.
kover {
  reports {
    total {
      providers.gradleProperty("kover.additionalBinaryReportsDir").orNull?.let { reportsDir ->
        additionalBinaryReports.addAll(
          fileTree(reportsDir) { include("**/*.ic") },
        )
      }
    }
  }
}
