#!/usr/bin/env python3
"""Generate tokenizer-private Unicode 16 tables from the verified Rust crate."""
import argparse
import hashlib
import re
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--unicode-source", required=True, type=Path)
parser.add_argument("--output", required=True, type=Path)
args = parser.parse_args()
source = args.unicode_source.read_bytes()
expected = "e229fbbc93599c5df42c174bdf77602ced0789e1e1c73f7b979a725a56c92da1"
if hashlib.sha256(source).hexdigest() != expected:
    raise SystemExit("Source is not pinned unicode-segmentation 1.12.0 tables.rs")
text = source.decode("utf-8")
categories = re.search(r"pub enum GraphemeCat \{(.*?)\}", text, re.S).group(1)
names = re.findall(r"GC_(\w+)", categories)
def block(name):
    return text.split("const " + name + ":", 1)[1].split("&[", 2)[-1].split("];", 1)[0]
triple = r"\('\\u\{([0-9a-fA-F]+)\}',\s*'\\u\{([0-9a-fA-F]+)\}',\s*GC_(\w+)\)"
pair = r"\('\\u\{([0-9a-fA-F]+)\}',\s*'\\u\{([0-9a-fA-F]+)\}'\)"
graphemes = re.findall(triple, block("grapheme_cat_table"))
extends = re.findall(pair, block("InCB_Extend_table"))
# Rust Unicode escapes themselves contain }, so take the entire matches! line.
linkers = re.findall(r"\\u\{([0-9a-fA-F]+)\}", text.split("pub fn is_incb_linker", 1)[1].split("\n}", 1)[0])
for entries in [graphemes, extends]:
    previous = -1
    for low, high, *_ in entries:
        low, high = int(low, 16), int(high, 16)
        assert previous < low <= high <= 0x10FFFF
        previous = high
assert len(graphemes) == 1480 and len(extends) == 371 and len(linkers) == 6
lines = [
    "// Generated by scripts/generate-tokenizer-unicode.py; do not edit.",
    "// Copyright 2012-2018 The Rust Project Developers.",
    "// Derived from unicode-segmentation 1.12.0, Unicode 16.0.0.",
    "// MIT terms: docs/licenses/tokenizer-unicode-segmentation-MIT.txt.",
    "// Source SHA-256: " + expected,
    "package com.slukhayka.audiobooks.data.recommend", "",
    "internal object UnicodeGraphemeTables {",
]
lines += ["    const val " + name.upper() + " = " + str(i) for i, name in enumerate(names)]
lines += ["", "    private val categories = intArrayOf("]
lines += ["        0x" + low.upper() + ", 0x" + high.upper() + ", " + name.upper() + "," for low, high, name in graphemes]
lines += ["    )", "", "    private val incbExtends = intArrayOf("]
lines += ["        0x" + low.upper() + ", 0x" + high.upper() + "," for low, high in extends]
lines += ["    )", "", "    fun category(scalar: Int): Int {", "        val index = rangeIndex(categories, 3, scalar)", "        return if (index < 0) ANY else categories[index + 2]", "    }", "", "    fun isInCbExtend(scalar: Int): Boolean = rangeIndex(incbExtends, 2, scalar) >= 0", "", "    fun isInCbLinker(scalar: Int): Boolean = when (scalar) { " + ", ".join("0x"+x.upper() for x in linkers) + " -> true; else -> false }", "", "    private fun rangeIndex(table: IntArray, stride: Int, scalar: Int): Int {", "        var low = 0", "        var high = table.size / stride - 1", "        while (low <= high) {", "            val middle = (low + high) ushr 1", "            val index = middle * stride", "            when {", "                scalar < table[index] -> high = middle - 1", "                scalar > table[index + 1] -> low = middle + 1", "                else -> return index", "            }", "        }", "        return -1", "    }", "}"]
args.output.write_text("\n".join(lines) + "\n")
print("Generated", len(graphemes), "grapheme ranges,", len(extends), "InCB Extend ranges,", len(linkers), "linkers")
