#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — spec-40 #283: контрольна матриця правил Firestore на staging.
# 14 рядків: book_reviews (10) + device_bindings (4), Rules playground.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
TOTAL_MINUTES=17

REPORT="docs/audits/$(date +%Y-%m-%d)-spec40-rules-matrix.md"
mkdir -p "$(dirname "$REPORT")"

banner "spec-40 #283 — матриця правил Firestore (staging)"

# ── Stage 1: правила задеплоєні й свіжі ───────────────────────────────────
stage "Правила на staging свіжі" 3
say "Мета: у консолі staging-проєкту задеплоєні саме ті правила, що в репо"
say "(firestore.rules, шапка зі згадкою Spec-40 #277/#276)."
ask FIREBASE_PROJECT_ID "Id staging-проєкту Firebase (з консолі, напр. slukhayka-staging):"
open_url "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID:-}/firestore/rules"
step "Звірь версію: у шапці правил у консолі має бути коментар"
note "   «Spec-40 #277 — the shape gate for one listener review»"
note "   і блок match /book_reviews/ + match /device_bindings/."
step "Якщо консоль відстає від репо — задеплой:"
note "   firebase deploy --only firestore --project ${FIREBASE_PROJECT_ID:-<staging-id>}"
note "   (або встав вміст firestore.rules у редактор консолі й Publish)."
if confirm "Правила в консолі тепер ідентичні репозиторійним?"; then
  say "Добре — рухаємось далі."
else
  warn "Без свіжих правил матриця виміряє не те. Заверши деплой і перезапусти."
  exit 1
fi

# ── Stage 2: матриця book_reviews (10 рядків) ─────────────────────────────
stage "Матриця book_reviews — Rules playground" 8
say "Вкладка Rules → панель Rules playground (внизу). Для кожного рядка:"
step "Location: шлях із рядка нижче (префікс /databases/(default)/documents/)."
step "App Check token: перемикач ON/OFF як у рядку."
step "Firebase Authentication: OFF = «signed out», ON = provider Custom,"
note "   uid = значення з рядка (uid-alice або uid-bob)."
step "Request method і body — з рядка. Run, порівняй із «Очікувано»."
printf '\n'
warn "ВАЖЛИВО перед R6–R9: симуляція UPDATE/DELETE читає resource.data,"
warn "тож документи мусять ІСНУВАТИ. У Firestore → почни колекцію"
warn "book_reviews і додай чотири документи з полем uid (string):"
note "   qa_r6, qa_r7, qa_r8, qa_r9 — в усіх uid = \"uid-alice\""
note "(для R7/R9 викликач uid-bob, а збережений uid лишається alice —"
note " у цьому й перевірка володіння)."

BODY_OWN='{"workId":"qa-work","uid":"uid-alice","authorName":"QA","rating":5,"createdAt":1700000000000}'
say "Тіло для CREATE/UPDATE (валідне):"
note "   $BODY_OWN"
say "Тіло для «malformed» рядка — те саме, але rating 9."

MATRIX_REVIEWS=(
  "R1|book_reviews/qa_r1|GET|signed-out|OFF|-|ALLOW|читання публічне"
  "R2|book_reviews/qa_r2|CREATE|uid-alice|ON|валідне|ALLOW|свій uid + AppCheck"
  "R3|book_reviews/qa_r3|CREATE|uid-bob|ON|валідне (uid=uid-alice)|DENY|чужий uid"
  "R4|book_reviews/qa_r4|CREATE|uid-alice|OFF|валідне|DENY|нема AppCheck-токена"
  "R5|book_reviews/qa_r5|CREATE|signed-out|ON|валідне (uid=uid-alice)|DENY|нема auth"
  "R6|book_reviews/qa_r6|UPDATE|uid-alice|ON|валідне|ALLOW|свій uid, документ створений вище"
  "R7|book_reviews/qa_r7|UPDATE|uid-bob|ON|валідне (uid=uid-alice)|DENY|чужий uid, документ створений вище"
  "R8|book_reviews/qa_r8|DELETE|uid-alice|ON|-|ALLOW|свій uid, документ створений вище"
  "R9|book_reviews/qa_r9|DELETE|uid-bob|ON|-|DENY|чужий uid, документ створений вище"
  "R10|book_reviews/qa_r10|CREATE|uid-alice|ON|malformed (rating 9)|DENY|форма не пройде"
)

RESULTS=()
for row in "${MATRIX_REVIEWS[@]}"; do
  IFS='|' read -r id path method auth appcheck payload expect why <<< "$row"
  printf '\n  %s%s — %s%s\n' "$BOLD" "$id" "$why" "$RESET"
  note "   path:    $path"
  note "   method:  $method · auth: $auth · AppCheck: $appcheck"
  [[ "$payload" != "-" ]] && note "   body:    $payload"
  say "Очікувано: $expect"
  if confirm "Фактичний результат збігся ($expect)?"; then
    RESULTS+=("| $id | \`$method $path\` | $auth | $appcheck | $expect | $expect | ✅ |")
  else
    local_actual=""
    ask local_actual "Що показав playground замість $expect (одним рядком):"
    RESULTS+=("| $id | \`$method $path\` | $auth | $appcheck | $expect | ${local_actual:-інше} | ❌ |")
  fi
done

# ── Stage 3: матриця device_bindings (4 рядки) ────────────────────────────
stage "Матриця device_bindings — Rules playground" 4
say "Та сама панель playground. Тіло для CREATE:"
note '   {"uid":"uid-alice","cred":"sealed-bytes"}'

MATRIX_BINDINGS=(
  "D1|device_bindings/qa_d1|GET|signed-out|OFF|-|ALLOW|читання публічне (до auth)"
  "D2|device_bindings/qa_d2|CREATE|uid-alice|ON|uid=uid-alice|ALLOW|свій uid"
  "D3|device_bindings/qa_d3|CREATE|uid-bob|ON|uid=uid-alice|DENY|чужий uid"
  "D4|device_bindings/qa_d4|CREATE|uid-alice|OFF|uid=uid-alice|DENY|нема AppCheck-токена"
)

for row in "${MATRIX_BINDINGS[@]}"; do
  IFS='|' read -r id path method auth appcheck payload expect why <<< "$row"
  printf '\n  %s%s — %s%s\n' "$BOLD" "$id" "$why" "$RESET"
  note "   path:    $path"
  note "   method:  $method · auth: $auth · AppCheck: $appcheck"
  [[ "$payload" != "-" ]] && note "   body:    $payload"
  say "Очікувано: $expect"
  if confirm "Фактичний результат збігся ($expect)?"; then
    RESULTS+=("| $id | \`$method $path\` | $auth | $appcheck | $expect | $expect | ✅ |")
  else
    local_actual=""
    ask local_actual "Що показав playground замість $expect (одним рядком):"
    RESULTS+=("| $id | \`$method $path\` | $auth | $appcheck | $expect | ${local_actual:-інше} | ❌ |")
  fi
done

# ── Stage 4: звіт ──────────────────────────────────────────────────────────
stage "Звіт у docs/audits + комент у #283" 2
{
  echo "# Матриця правил Firestore — spec-40 #283"
  echo
  echo "Дата: $(date +%Y-%m-%d). Staging, Rules playground. Очікування зумовлені"
  echo "firestore.rules у репозиторії (book_reviews #277, device_bindings #276)."
  echo
  echo "| № | Операція | auth | AppCheck | Очікувано | Факт | OK |"
  echo "|---|---|---|---|---|---|---|"
  for line in "${RESULTS[@]}"; do echo "$line"; done
  echo
  echo "Глосарій (CONTEXT.md: «Відгук», «Код відновлення», примітка Source"
  echo "Binding) і розкриття приватності в README закриті комітом 81c8fa8."
} > "$REPORT"
printf '  %s✓ звіт записано%s %s\n' "$GREEN" "$RESET" "$REPORT"

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if confirm "Додати звіт коментарем до issue #283?"; then
    if gh issue comment 283 --body-file "$REPORT" >/dev/null 2>&1; then
      printf '  %s✓ комент опубліковано%s\n' "$GREEN" "$RESET"
    else
      SKIPPED+=("комент у #283 — встав $REPORT вручну")
      warn "не вдалося опублікувати комент — зроби це вручну"
    fi
  fi
else
  SKIPPED+=("комент у #283 — встав $REPORT вручну (gh недоступний)")
fi

if confirm "Закрити issue #283 (усі критерії виконано)?"; then
  gh issue close 283 --comment "Матрицю правил прогнано на staging — звіт у docs/audits і в коментарях вище. Глосарій + розкриття — 81c8fa8. Розбіжностей нема." 2>/dev/null \
    || warn "не вдалося закрити #283 автоматично"
fi

finish
